### ISSUE TITLE
Bad Gateway returned when not in debug mode

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#117]
This is what I did.
1) I setup a new AKS cluster (RBAC enabled)
2) I enabled Dev Spaces on it
3) I created a ASP.Net Core 2.2 Web Project
4) I started the project with the option to debug it in "Azure Dev Spaces" with "Public" selected
5) The project started fine and the web page was shown (http://default.webk8.54fqhtlhqv.weu.azds.io/)
6) I stoped the debugger

Now my web page returns "Bad Gateway" and the "devspaces-proxy" log returns this:
```
Accepted outer connection from 10.244.0.17:47390
Error opening inner connection for 10.244.0.17:47390 to 10.244.0.169:80: Connection refused 10.244.0.169:80
Reset outer connection from 10.244.0.17:47390
Disposed connections related to 10.244.0.17:47388
```

Shouldn't I be able to access the page even after I stoped debugging or am I missing something here ?

**Comment by stepro** [comment]
Dev Spaces is supposed to restart the original process in the container after a debug session ends. Sometimes this can take a little time, but it seems like you are getting the error persistently. Is there anything in the stdout log from the pod that would indicate whether the process got restarted?

**Comment by Eneuman** [comment]
I can't find any information about a process getting started.
The only thing I see is:
```
The inner connection from 10.244.0.127:39241 was closed 
Disposed connections related to 10.244.0.127:39241 
```

and that's coming from devspaces-proxy.
(I'm using log viewer from inside Azure for the k8 cluster)

**Comment by Eneuman** [comment]
This is driving me nuts...

I removed my intire AKS cluster.
I then recreated a new cluster using the Azure portal (West Europe) with RBAC not enabled.
I then enabled dev spaces using the azure portal.
After that I created a new ASP.Net Core Web Project and selected my AKS Dev Space using the "default" namespace.

Same problem again. I can view the site when debuging. 
When I stop debugging, I get a "Bad Gateway" back.

@stepro Can you please try and reproduce this and see if it works on your end?

**Comment by xinyanmsft** [comment]
Eneuman, are you using Visual Studio or VSCode? If you use Visual Studio, can you upgrade to latest extension? We had a bug (fixed around early March) that could cause something like this.
Otherwise, DevSpace tries to restart the process after debugging. If you execute into the container (e.g., using 'kubectl exec' command or via the K8s dashboard), do a 'ps aux' and check whether the desired process is running or not. My guess is, it is not running. 
The command we use to restart the process in defined in the 'azds.yaml' file, such as:
        command: [dotnet, run, --no-restore, --no-build, --no-launch-profile, -c, "${BUILD_CONFIGURATION:-Debug}"]
if this command is incorrect, or it crashes, you will also see a behavior like this. Try run this command in the container and does it work?

**Comment by Eneuman** [comment]
Im using VS 2019 with latest version of the DevSpaces extension.
PS Aux shows me this:

USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0   4280   736 ?        Ss   21:09   0:00 sh -c /.azds-agent/azds-agent.sh run > /tmp/devhostagent.log
root         12  0.0  0.0   4280   708 ?        S    21:09   0:00 /bin/sh /.azds-agent/azds-agent.sh run
root         14  0.3  1.1 11785344 92032 ?      Sl   21:09   0:03 /.azds-agent/linux/azds-agent run
root        350  0.0  0.0  36636  2912 ?        Rs   21:26   0:00 ps aux

**Comment by xinyanmsft** [comment]
what's your Dockerfile.develop and azds.yaml looks like?

**Comment by Eneuman** [comment]
Vanilla:

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["WebK8/WebK8.csproj", "WebK8/"]

RUN dotnet restore "WebK8/WebK8.csproj"
COPY . .
WORKDIR "/src/WebK8"
RUN dotnet build --no-restore "WebK8.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]

```

```
kind: helm-release
apiVersion: 1.1
build:
  context: ..
  dockerfile: Dockerfile
install:
  chart: charts/webk8
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: webk8
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to form the service's public URL: [space.s.][rootSpace.]webk8.<random suffix>.<region>.azds.io
      # Customize the public URL by changing the 'webk8' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
      # For more information see https://aka.ms/devspaces/routing
      - $(spacePrefix)$(rootSpacePrefix)webk8$(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    container:
      sync:
      - "**/Pages/**"
      - "**/Views/**"
      - "**/wwwroot/**"
      - "!**/*.{sln,csproj}"
      command: [dotnet, run, --no-restore, --no-build, --no-launch-profile, -c, "${BUILD_CONFIGURATION:-Debug}"]
      iterate:
        processesToKill: [dotnet, vsdbg]
        buildCommands:
        - [dotnet, build, --no-restore, -c, "${BUILD_CONFIGURATION:-Debug}"]

```
