### ISSUE TITLE
Add support for multiple project azds debug configuration on vscode extension

### ISSUE THREAD

**Issue by feroz-ahmmed** [Azure/dev-spaces#120]
I have a dotnet solution with multiple projects under it. 
service.sln
--> service.API.csproj
--> sevice.Model.csproj

How do I crate initial templates for azds for this?

**Comment by ynambiar** [comment]
Thanks for your question @feroz-ahmmed! 

Assuming you've enabled the Azure Dev Spaces extension for VS Code, you should be able to prep the second project by following these steps:

- Open the first project in VS Code
- Add the second project by going to 'File > Add Folder to Workspace...'
- To prepare the config files for the second project, go to 'View > Command Palette > select 'Azure Dev Spaces: Prepare configuration files or Azure Dev Spaces' > select the second project

Hope this works for you!

**Comment by feroz-ahmmed** [comment]
@ynambiar , I only need azds configuration for service.API project. But this project have reference of service.Model project. My problem is the auto generated files (i.e - Dockerfile) are not considering the referenced projects. I also intend to have support for remote debugging as well on launch configuration for vscode such that I can have my debugger attached on both of my projects.

**Comment by feroz-ahmmed** [comment]
@ynambiar , It looks like visual studio 2017 is doing everything perfectly with their extension for kubernetes as we have the context of a solution there. But vscode is being a bit naive here.

**Comment by ynambiar** [comment]
@feroz-ahmmed, that makes sense. We are actually working on this feature now, and will update here when it's in production. Thanks!

**Comment by robertjf** [comment]
@ynambiar I've been looking into this issue as well - is it possible to have the tooling for VS Code generate the launch and tasks in .vscode from a Solution instead of a project?  It seems like a logical thing to do for me.  When I try to prep the primary project (sitting in a sub directory) it creates the azds.yaml and docker.develop files, but doesn't go far enough to create the debug configuration.  I've tried manually creating it from the sample project setup, and have had to tweak the docker.develop file as well, but am stuck with the paths I think - I get the following error after it's succesfully created the docker image:
```
Starting: "azds" exec --interactive --on-exit-resume-up --verbose -- /vsdbg/vsdbg --interpreter=vscode
Error from pipe program 'azds': No such file or directory
```

**Comment by daniv-msft** [comment]
As of today, the easiest way to make solutions work with our VS Code extension is to open its projects as workspaces in Visual Studio Code. That way, it is possible to prep and debug them in a somewhat similar way as what we would have with a solution.
Please note though that we don't handle well upgrades of azds.yaml files in multi-workspaces scenarios, which may cause confusion. We have a fix for this, that will be released in the coming days.

@robertjf Regarding your question about vsdbg, I will let other persons knowing more about this answer.

**Comment by xinyanmsft** [comment]
@robertjf when you have the 'vsdbg' problem with VSCode, there should be a 'azds' process running on your machine, and the command line argument looks something like 'azds daemon ...'. What is the full command line argument for that process?
If you are using Windows, go to 'Task Manager' and look for 'azds.exe' processes, one of them should have argument 'azds.exe daemon ...'. If you are using Mac, do 'ps aux | grep azds'. Thanks!

**Comment by robertjf** [comment]
@xinyanmsft I managed to get it working by setting the VS Code workspace to the API project directory and running the `>Azure Dev Spaces: Prepare configuration files for Azure Dev Spaces` command from there - everything worked out of the box, all I had to do was delete the generated charts directory as I'm using charts from a different repository and have already set up the azds.yaml file for that.

The problem I have with this approach is that I lose visibility on the supporting project source code.  My solution structure is as follows:

```
- AddressBook.API
    |   AddressBook.sln
    + src
        + AddressBook
            + AddressBook.API
            |   azds.yaml
            |   AddressBook.API.csproj
            |   Dockerfile.develop
            |   values.dev.yaml
            |   nuget.develop.config
            + AddressBook.Infrastructure
            |   AddressBook.Infrastructure.csproj
            + AddressBook.Domain
            |   AddressBook.Domain.csproj
```

Ideally, I'd like to be able to have the workspace mirror this structure and still be able to debug the AddressBook.API project as the entry point.

For reference, my azds.yaml and Dockerfile.develop currently look like this (loosely based on the eShopOnContainers solution):

```yaml
kind: helm-release
apiVersion: 1.1
build:
  context: ../../../../
  dockerfile: Dockerfile
install:
  chart: ../../../../../HelmCharts/charts/addressbook-api
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      - $(spacePrefix)$(rootSpacePrefix)medipulse$(hostSuffix)
    inf:
      k8s:
        dns: $(spacePrefix)$(rootSpacePrefix)medipulse$(hostSuffix)
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  - ../../../../../HelmCharts/charts/inf.yaml
  - ../../../../../HelmCharts/charts/app.yaml
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
      ignore:
      - “!nuget.develop.config”
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    container:
      sync:
      - '**/Pages/**'
      - '**/Views/**'
      - '**/wwwroot/**'
      - '!**/*.{sln,csproj}'
      command: [dotnet, run, --no-restore, --no-build, --no-launch-profile, -c, "${BUILD_CONFIGURATION:-Debug}"]
      iterate:
        processesToKill: [dotnet, vsdbg, addressbook]
        buildCommands:
        - [dotnet, build, --no-restore, -c, "${BUILD_CONFIGURATION:-Debug}"]
```

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

#RUN apt update && \
#    apt install unzip && \
#    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

WORKDIR /src
COPY ["src/Services/AddressBook/AddressBook.API", "AddressBook.API/"]
COPY ["src/Services/AddressBook/AddressBook.Infrastructure", "AddressBook.Infrastructure/"]
COPY ["src/Services/AddressBook/AddressBook.Domain", "AddressBook.Domain/"]

WORKDIR /src/AddressBook.API
RUN dotnet restore AddressBook.API.csproj --configfile nuget.develop.config

RUN dotnet build --no-restore -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]
```

I've commented out the command to install vsdbg as it's now working correctly in this configuration.

I also noticed that since getting this running at the project level, if I go back to my solution-level Workspace, it now also works with one exception - the debugger launches properly, and azds properly syncs and connects to the dev space; however there is no related Output log I can go to inspect the services and their respective urls:

![Available output log options](https://user-images.githubusercontent.com/818101/61585226-2e343f00-ab9a-11e9-92e6-47445031cb3e.png)

So not really sure what's changed other than configuring azds at the project level; and I can't replicate the errors I was getting before at the solution level.

For reference, here's my launch and task at the solution level:

launch.json:
```json
{
vscode/blob/master/debugger-launchjson.md
   "version": "0.2.0",
   "configurations": [
        {
           "name": ".NET Core Launch (AZDS)",
           "type": "coreclr",
           "request": "launch",
           "preLaunchTask": "azds: prelaunch",
           "pipeTransport": {
               "pipeCwd": "${workspaceFolder}/src/Services/AddressBook/AddressBook.API/",
               "pipeProgram": "azds",
               "pipeArgs": [
                   "exec",
                   "--interactive",
                   "--verbose",
                   "--on-exit-resume-up",
                   "--"
               ],
               "debuggerPath": "/vsdbg/vsdbg",
               "quoteArgs": false
           },
           "cwd": "/src/AddressBook.API/",
           "program": "/src/AddressBook.API/bin/Debug/netcoreapp2.2/AddressBook.API.dll",
           "sourceFileMap": {
               "/src": "${workspaceFolder}/src/Services/AddressBook/."
           }
        }
    ]
}
```
tasks.json:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "azds: prelaunch",
            "command": "azds",
            "args": [
                "up",
                "--await-exec",
                "--keep-alive"
            ],
            "options": {
                "cwd": "${workspaceFolder}/src/Services/AddressBook/AddressBook.API/"
            },
            "problemMatcher": "$msCompile"
        }
    ]
}
```
