### ISSUE TITLE
Including a gitignored file not working

### ISSUE THREAD

**Issue by robertjf** [Azure/dev-spaces#138]
I have an azds that contains the following snippet:

```yaml
build:
  useGitIgnore: true
  ignore:
  - "!nuget.develop.config"
```
however the ignored (in .gitignore) file is still not being copied into the docker image to be used while building.  I've tried several versions including the following as indicated in this documentation (which looks wrong by the way):
```yaml
build:
useGitIgnore: true
ignore:
- "!nuget.develop.config"
```
I've tried several things with the file listed in the .gitignore including:
```docker
COPY ["src/Services/Versioning/Versioning.API/nuget.develop.config", "Services/Versioning/Versioning.API/"]
```
which fails with 
```
COPY failed: stat /var/lib/docker/tmp/docker-builder057519705/src/Services/Versioning/Versioning.API/nuget.develop.config: no such file or directory
```

Once I comment out the entry in .gitignore though everything starts working.

**Comment by robertjf** [comment]
I initially reported this over at the documentation issue tracker: https://github.com/MicrosoftDocs/azure-docs/issues/35159

**Comment by feroz-ahmmed** [comment]
Our team also facing the same issue. Why no one is replying to this thread? We decided to use dev spaces as much as we can. Maybe we need to rethink about it.

**Comment by stepro** [comment]
According to the issue linked by @robertjf, this is an outstanding issue with the Dev Spaces client, which has an incorrect ordering of rules. As @xinyanmsft said, it should apply .gitignore first, then .dockerignore, then azds.yaml ignore rules. This was the original design, so something regressed.

I can confirm that the internal work item was resolved at the end of July, so it should be showing up in production shortly.

**Comment by robertjf** [comment]
that's great news @stepro - thank you so much :)

**Comment by YuzorMa** [comment]
This should be fixes in the latest version of the CLI (1.0.20190904.13)

**Comment by ruwentos** [comment]
I'm using:
Azure Dev Spaces CLI
1.0.20200827.4
API v3.2

The problem is still there.

My azds.yaml:
 ```
build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
      ignore:
      - "!NuGet.Config"
```
When I comment out the .gitignore rule, it works.

What's the story on that fix?
