### ISSUE TITLE
Build fails when using imagePullSecrets

### ISSUE THREAD

**Issue by jdharmon** [Azure/dev-spaces#155]
Container images fail to build when values are specified for `imagePullSecrets` in `values.yaml`. 

**values.yaml**
```yaml
image:
  repository: stihldev/ebaa-api
  tag: latest
  pullPolicy: IfNotPresent
imagePullSecrets:
 - name: docker-hub
```

```
> azds up
Using dev space 'jason' with target 'web-aks-stihldev-d'
Synchronizing files...5s
Installing Helm chart...2s
Waiting for container image build...
pods/ebaa-api-d9c958566-m4wr2: FailedMount: MountVolume.SetUp failed for volume "azds-docker-hub" : secrets "docker-hub" not found
pods/ebaa-api-d9c958566-m4wr2: FailedMount: Unable to mount volumes for pod "ebaa-api-d9c958566-m4wr2_jason(5ffdaa25-d0d3-11e9-add3-5228355e5fb6)": timeout expired waiting for volumes to attach or mount for pod "jason"/"ebaa-api-d9c958566-m4wr2". list of unmounted volumes=[azds-docker-hub]. list of unattached volumes=[default-token-j9vxb azds-docker-hub devspaces-startcmd devspaces-docker-sock aks-sp tool-mount-0]
```

The build just hangs at this point.
