### ISSUE TITLE
Error "Unable to find fallback package folder"

### ISSUE THREAD

**Issue by econforti** [Azure/dev-spaces#337]
I am following the tutorial "https://microsoft.github.io/AzureTipsAndTricks/blog/tip228.html" to use Azure Dev Spaces (using a scaffolding Aspnet.core WebAPI WeatherForecast in place the git sample in the tutorial), but stucked on the step to run "azds up":

azds up --verbose
Using dev space 'dev' with target 'userxxx-cluster-k8s'
Synchronizing files...3s
Installing Helm chart...
Release "azds-8eb137-dev-frontuserxxxweather" has been upgraded.
LAST DEPLOYED: Thu Apr  9 12:28:37 2020
NAMESPACE: dev
STATUS: DEPLOYED
RESOURCES:
==> v1/Deployment
NAME                READY  UP-TO-DATE  AVAILABLE  AGE
frontuserxxxweather  0/1    0           0          40h
==> v1/Pod(related)
NAME                                 READY  STATUS    RESTARTS  AGE
frontuserxxxweather-6d9dd85bb5-lb7df  0/2    Init:0/3  0         5m45s
==> v1/Service
NAME                TYPE       CLUSTER-IP  EXTERNAL-IP  PORT(S)  AGE
frontuserxxxweather  ClusterIP  10.10.76.17   <none>       80/TCP   40h
==> v1beta1/Ingress
NAME                AGE
frontuserxxxweather  40h
NOTES:
1. Get the application URL by running these commands:
  https://dev.frontuserxxxweather.qpj4bsn4d2.wus2.azds.io/
Installed chart in 2s
Waiting for container image build...
pods/frontuserxxxweather-6d9dd85bb5-lb7df: Scheduled: Successfully assigned dev/frontuserxxxweather-6d9dd85bb5-lb7df to aks-agentpool-27655216-0
pods/frontuserxxxweather-6d9dd85bb5-lb7df: Pulled: Container image "azds/azds-build-service:20200316.1" already present on machine    
pods/frontuserxxxweather-6d9dd85bb5-lb7df: Created: Created container devspaces-build
pods/frontuserxxxweather-6d9dd85bb5-lb7df: Started: Started container devspaces-build
pods/frontuserxxxweather-cc44d48d-pdnzd: Scheduled: Successfully assigned dev/frontuserxxxweather-cc44d48d-pdnzd to aks-agentpool-27655216-0
pods/frontuserxxxweather-cc44d48d-pdnzd: Pulled: Container image "azds/azds-build-service:20200316.1" already present on machine
pods/frontuserxxxweather-cc44d48d-pdnzd: Created: Created container devspaces-build
pods/frontuserxxxweather-cc44d48d-pdnzd: Started: Started container devspaces-build
Finished waiting for container image build in 4s
Building container image...
Sending build context to Docker daemon  1.368MB
Step 1/13 : FROM mcr.microsoft.com/dotnet/core/sdk:3.1
---> fc3ec13a2fac
Step 2/13 : ARG BUILD_CONFIGURATION=Debug
---> Using cache
---> c4c9208d24d6
Step 3/13 : ENV ASPNETCORE_ENVIRONMENT=Development
---> Using cache
---> e33f660e05ca
Step 4/13 : ENV ASPNETCORE_URLS=https://+:80
---> Using cache
---> 2387aa0666d0
Step 5/13 : ENV DOTNET_USE_POLLING_FILE_WATCHER=true
---> Using cache
---> b7cdcb0e4fb5
Step 6/13 : EXPOSE 80
---> Using cache
---> 78eebbf1ccab
Step 7/13 : WORKDIR /src
---> Using cache
---> fbe5f2456cbb
Step 8/13 : COPY ["FrontuserxxxWeather.csproj", "./"]
---> Using cache
---> ed718c30bd86
Step 9/13 : RUN dotnet restore "FrontuserxxxWeather.csproj"
---> Using cache
---> f1ee4bebdd3f
Step 10/13 : COPY . .
---> Using cache
---> 054b9f7b663a
Step 11/13 : RUN dotnet build --no-restore -c $BUILD_CONFIGURATION
---> Running in 3390b90f3faa
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder'. [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders) [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders) [/src/FrontuserxxxWeather.csproj]      
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(LockFile lockFile) [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task) [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash) [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) [/src/FrontuserxxxWeather.csproj]      
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/src/FrontuserxxxWeather.csproj]   
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/src/FrontuserxxxWeather.csproj]
Build FAILED.
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018: NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder'. [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders) [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders) [/src/FrontuserxxxWeather.csproj]      
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(LockFile lockFile) [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task) [/src/FrontuserxxxWeather.csproj]      
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash) [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) [/src/FrontuserxxxWeather.csproj]      
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/src/FrontuserxxxWeather.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/src/FrontuserxxxWeather.csproj]   
/usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error MSB4018:    
at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/src/FrontuserxxxWeather.csproj]
0 Warning(s)
1 Error(s)
Time Elapsed 00:00:00.39
The command '/bin/sh -c dotnet build --no-restore -c $BUILD_CONFIGURATION' returned a non-zero code: 1

The mentioned folder 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder' exist, so, tried to give full permission, delete obj and bin folders, restart SO and the suggestions gived here

https://github.com/dotnet/sdk/issues/9180

and here

https://github.com/NuGet/Home/issues/7012

Running "dotnet msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=a.dg" produces:

{
  "format": 1,
  "restore": {
    "C:\\Users\\userxxx\\source\\repos\\WebAppuserxxxWeather\\FrontuserxxxWeather\\FrontuserxxxWeather.csproj": {}
  },
  "projects": {
    "C:\\Users\\userxxx\\source\\repos\\WebAppuserxxxWeather\\FrontuserxxxWeather\\FrontuserxxxWeather.csproj": {
      "version": "1.0.0",
      "restore": {
        "projectUniqueName": "C:\\Users\\userxxx\\source\\repos\\WebAppuserxxxWeather\\FrontuserxxxWeather\\FrontuserxxxWeather.csproj",
        "projectName": "FrontuserxxxWeather",
        "projectPath": "C:\\Users\\userxxx\\source\\repos\\WebAppuserxxxWeather\\FrontuserxxxWeather\\FrontuserxxxWeather.csproj",
        "packagesPath": "C:\\Users\\userxxx\\.nuget\\packages\\",
        "outputPath": "C:\\Users\\userxxx\\source\\repos\\WebAppuserxxxWeather\\FrontuserxxxWeather\\obj\\",
        "projectStyle": "PackageReference",
        "fallbackFolders": [
          "C:\\Program Files\\dotnet\\sdk\\NuGetFallbackFolder",
          "C:\\Program Files (x86)\\Microsoft SDKs\\NuGetPackagesFallback\\"		  
        ],
        "configFilePaths": [
          "C:\\Users\\cipop.CORP\\AppData\\Roaming\\NuGet\\NuGet.Config",
          "C:\\Program Files (x86)\\NuGet\\Config\\Microsoft.VisualStudio.Offline.config"
        ],
        "originalTargetFrameworks": [
          "netcoreapp3.1"
        ],
        "sources": {
          "C:\\Program Files (x86)\\Microsoft SDKs\\NuGetPackages\\": {},
          "https://api.nuget.org/v3/index.json": {}
        },
        "frameworks": {
          "netcoreapp3.1": {
            "projectReferences": {}
          }
        },
        "warningProperties": {
          "warnAsError": [
            "NU1605"
          ]
        }
      },
      "frameworks": {
        "netcoreapp3.1": {
          "dependencies": {
            "Microsoft.VisualStudio.Azure.Containers.Tools.Targets": {
              "target": "Package",
              "version": "[1.9.10, )"
            }
          },
          "imports": [
            "net461",
            "net462",
            "net47",
            "net471",
            "net472",
            "net48"
          ],
          "assetTargetFallback": true,
          "warn": true,
          "frameworkReferences": {
            "Microsoft.AspNetCore.App": {
              "privateAssets": "none"
            },
            "Microsoft.NETCore.App": {
              "privateAssets": "all"
            }
          },
          "runtimeIdentifierGraphPath": "C:\\Program Files\\dotnet\\sdk\\3.1.101\\RuntimeIdentifierGraph.json"
        }
      }
    }
  }
}

**Environment Details**

Windows 10 Pro
VS Code (1.44.0) with extension azuredevspaces.azds@2.0.220200429 
Azure Dev Spaces (1.0.20200331.2 / API v3.2)
Docker Desktop for Linux Containers (2.2.0.4 and engine 19.03.8).

Any ideia? Thanks!

**Comment by Eneuman** [comment]
Where are the NuGet packages located? NuGet.org, local disk or Azure?

(The build is taking place inside a docker container in you k8 cluster and not on your local machine)

**Comment by econforti** [comment]
The machine is configured to use an Azure private feed for another project ("nuget.exe sources Add" in console), but the current project is a fresh one genereted by VS scaffolding (without dependencies). I can't figure out yet what is wrong, so, any suggestion of what i might try?

**Comment by Eneuman** [comment]
Are you using any of the packages from your private feed in the project?
Do you have a NuGet.config file in your solution?

**Comment by econforti** [comment]
No for both.

**Comment by Eneuman** [comment]
Can you share your .csproj file here?

________________________________
Från: Eduardo Conforti <notifications@github.com>
Skickat: Monday, May 18, 2020 2:47:52 PM
Till: Azure/dev-spaces <dev-spaces@noreply.github.com>
Kopia: Per Bornsjö <per.bornsjo@links.se>; Comment <comment@noreply.github.com>
Ämne: Re: [Azure/dev-spaces] Error "Unable to find fallback package folder" (#337)


No for both.

**Comment by econforti** [comment]
Here is:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.10" />
  </ItemGroup>

</Project>
```

**Comment by Eneuman** [comment]
Can you post your .dockerignore as well?

**Comment by econforti** [comment]
.dockerignore:

```
**/.classpath
**/.dockerignore
**/.env
**/.git
**/.gitignore
**/.project
**/.settings
**/.toolstarget
**/.vs
**/.vscode
**/*.*proj.user
**/*.dbmdl
**/*.jfm
**/azds.yaml
**/bin
**/charts
**/docker-compose*
**/Dockerfile*
**/node_modules
**/npm-debug.log
**/obj
**/out
**/secrets.dev.yaml
**/values.dev.yaml
.dotnet
.Microsoft.DotNet.ImageBuilder
LICENSE
README.md
```
.Dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["FrontuserxxxWeather/FrontuserxxxWeather.csproj", "FrontuserxxxWeather/"]
RUN dotnet restore "FrontuserxxxWeather/FrontuserxxxWeather.csproj"
COPY . .
WORKDIR "/src/FrontuserxxxWeather"
RUN dotnet build "FrontuserxxxWeather.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FrontuserxxxWeather.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FrontuserxxxWeather.dll"]
```

.Dockerfile.Development:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["FrontuserxxxWeather.csproj", "./"]
RUN dotnet restore "FrontuserxxxWeather.csproj"
COPY . .
RUN dotnet build --no-restore -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION -- \"\$@\"" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
```

and azds.yaml:

```
kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/frontuserxxxweather
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    # Optionally, specify an array of imagePullSecrets. These secrets must be manually created in the namespace.
    # This will override the imagePullSecrets array in values.yaml file.
    # If the dockerfile specifies any private registry, the imagePullSecret for that registry must be added here.
    # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
    #
    # For example, the following uses credentials from secret "myRegistryKeySecretName".
    #
    # imagePullSecrets:
    #   - name: myRegistryKeySecretName
    replicaCount: 1
    image:
      repository: frontuserxxxweather
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to form the service's public URL: [space.s.][rootSpace.]frontuserxxxweather.<random suffix>.<region>.azds.io
      # Customize the public URL by changing the 'frontuserxxxweather' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
      # For more information see https://aka.ms/devspaces/routing
      - $(spacePrefix)$(rootSpacePrefix)frontuserxxxweather$(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    container:
      sync:
      - "**/Pages/**"
      - "**/Views/**"
      - "**/wwwroot/**"
      - "!**/*.{sln,csproj}"
      command: [dotnet, run, --no-restore, --no-build, --no-launch-profile, -c, "${BUILD_CONFIGURATION:-Debug}"]
      iterate:
        processesToKill: [dotnet, vsdbg, FrontuserxxxWeather]
        buildCommands:
        - [dotnet, build, --no-restore, -c, "${BUILD_CONFIGURATION:-Debug}"]
```
