### ISSUE TITLE
vscode extension not compatible with AzureAD enabled clusters and newer kubectl

### ISSUE THREAD

**Issue by jon-walton** [Azure/dev-spaces#361]
**Describe the bug**

After installing the Dev-Spaces vscode extension, I am requested to login to the cluster every time I run `kubectl` for an AzureAD enabled cluster.
 
**To Reproduce**

- Run `kubectl get node` (successful)
- Download the CLI https://aka.ms/get-azds-windows
- Install the vscode extension
- Restart vscode
- Run `kubectl get node`
- Requested to login

Open `~/.kube/config` and note that the cluster under the `users` section no longer has `environment AzurePublicCloud`

Before:

```yaml
users:
- name: clusterUser_MyAksCluster
  user:
    auth-provider:
      config:
        access-token: [redacted]
        apiserver-id: [redacted]
        client-id: [redacted]
        environment: AzurePublicCloud
        expires-in: "3599"
        expires-on: "1592882029"
        refresh-token: [redacted]
        tenant-id: [redacted]
      name: azure
```

after:

```yaml
users:
- name: clusterUser_MyAksCluster
  user:
    auth-provider:
      config:
        access-token: [redacted]
        apiserver-id: [redacted]
        client-id: [redacted]
        expires-in: "3599"
        expires-on: "1592882029"
        refresh-token: [redacted]
        tenant-id: [redacted]
      name: azure
```

 
**Expected behavior**

Not remove the `environment` key from the config. This is caused by the CLI being built using an older Kubernetes client library

**Environment Details**
Client used (CLI/VS Code/Visual Studio): vscode v2.0.220200611

```
kubectl version --client --short
Client Version: v1.17.0
```

dev spaces cli: 1.0.4217.2
 
**Additional context**

Similar issue happened with Helm - https://github.com/helm/helm/issues/5665
