### ISSUE TITLE
[Dev Spaces] Container always getting rebuilt after code change in VS Code

### ISSUE THREAD

**Issue by arkadiyan** [Azure/dev-spaces#363]
**Describe the bug**
In VS Code for our C# project using F5 to debug triggers rebuilding container image every time a *.cs code file gets changed.
The correct behavior should be that after changing code it should not rebuild container image, but sync and restart process remotely in running container.
This causes code changes to take ~3-4 minutes to be reflected on the cluster, which is a real blocker for us.

On same machine it works perfectly fine with your sample application, where after changing a *.cs code file and restarting debugger, it does not rebuild container image, but restarts process remotely on the container, which takes only ~10 seconds total.

When stopping and starting debugger it shows following:

Starting to deploy the .NET Core application...
Waiting to update files in container...
Unable to determine sync target
File synchronization failed
Synchronizing files...1s
Using dev space 'arkadiya' with controller 'xyz'
Installing Helm chart...2s
Waiting for container image build...9s
Building container image...
...

However when restarting debugger in VS Code (not stopping and starting) it doesn't say sync failed:

Starting to deploy the .NET Core application...
Synchronizing files...1s
Using dev space 'arkadiya' with controller 'bonsai-staging-cni-kube'
Installing Helm chart...2s
Waiting for container image build...
...

In both cases container image gets rebuilt from scratch.

 
**To Reproduce**
.NET core application in C# with code in 'Controllers' folder. Run debugger in VS Code using Dev Spaces launch with F5. 
After service is up and debugger running, change a file in 'Controllers' folder. Restart debugger. Container image gets rebuild from scratch, even though 'Controllers' folder is included in azds.yaml 'sync' section.

 
**Expected behavior**
After changing code file and restarting debugger, the file should get synced and process in container rebuild and restarted remotely. No container image rebuild expected.
 
**Logs**
 
**Environment Details**
Client used (CLI/VS Code/Visual Studio):
CLI:
Azure Dev Spaces CLI
1.0.20200617.2
API v3.2

VS Code:
Version: 1.46.0
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T08:59:06.977Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
Azure Dev Spaces: v2.0.220200611
Azure Kubernetes Service: v0.0.6
 
**Additional context**

azds.yaml:

```
kind: helm-release
apiVersion: 1.1
build:
  context: ../../
  dockerfile: ../../Dockerfile
install:
  chart: charts/service/
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    image:
      repository: service
      tag: $(tag)
      pullPolicy: Never
    service:
      ingress:
        devSpacesBaseDomain: $(spacePrefix)$(rootSpacePrefix)xyz.com
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
      service:
        rest:
          externalPort: 80
      hpa:
        maxReplicas: 1
        minReplicas: 1
configurations:
  develop:
    build:
      context: ../../
      dockerfile: ../../Dockerfile.develop
      useGitIgnore: true
    container:
      sync:
      - "**/Controllers/**"
      - "**/Data/**"
      - "**/Filters/**"
      - "**/Handlers/**"
      - "**/Properties/**"
      - "**/Services/**"
      - "**/Utils/**"
      - "!**/*.{sln,csproj}"
      command: [dotnet, run, --no-restore, --no-build, --no-launch-profile, -c, Debug]
      iterate:
        processesToKill: [dotnet, vsdbg, Microsoft.Socrates.ControlPlane]
        buildCommands:
        - [dotnet, build, --no-restore, -c, Debug]
````

Dockerfile.develop:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build

ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true

WORKDIR /app/
COPY Service/Service/ ./Service/Service/

WORKDIR /app/Service/Service
RUN dotnet restore
RUN dotnet build --no-restore -c Debug

RUN echo "exec dotnet run --no-build --no-launch-profile -c Debug -- \"\$@\"" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
```

Dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build

WORKDIR /app/
COPY Service/Service/ ./Service/Service/

WORKDIR /app/Service/Service
RUN dotnet publish -c Release -o out --runtime linux-x64

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime
WORKDIR /app
COPY --from=build /app/Service/Service/out .
ARG BUILD_TIME=unset
ENV DOCKER_IMAGE_BUILD_TIME=${BUILD_TIME}
ARG BUILD_TAG=unset
ENV DOCKER_IMAGE_BUILD_TAG=${BUILD_TAG}
ENTRYPOINT ["dotnet", "ABC.ServiceXYZ.dll"]
```

**Comment by stepro** [comment]
@arkadiyan, looking at your Dockerfile, I notice you never copy the entire contents of the build context into the container (as in `COPY . <somewhere>`). Without this kind of statement, Dev Spaces is unable to automatically determine where your local build context files (under the `../../` directory you have specified in `azds.yaml`) should be copied to in the container. For these situations, you can specify a `syncTarget` property alongside the `sync` property in `azds.yaml` to say where the root of the build context would otherwise be in the container (in your case, I think this will be `/app`).

So something like this:

```
configurations:
  develop:
    build:
      context: ../../
      dockerfile: ../../Dockerfile.develop
      useGitIgnore: true
    container:
      syncTarget: /app
      sync:
      - "**/Controllers/**"
```

Please let me know if this doesn't work and we can debug further.
