### ISSUE TITLE
Values in install.set are wrongly set up in azds.yaml file

### ISSUE THREAD

**Issue by gionapaolini** [Azure/dev-spaces#364]
I have a chart where I have a hpa

```
{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
....
{{- end }}

```
My values.yaml contains this:

```
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

```
And if I deploy the chart with `helm install release-name .` it **is fine** and **does not** deploy the hpa.

Instead, if I use the azds.yaml:

```
install:
  chart: ./chart
  set:
    autoscaling: 
      enabled: false
   ...
```
for some reason the autoscaling.enabled evaluates to true when deploying the chart, and it deploys the hpa even if it should not do that.

Same thing happens for the ingress, it seems that as soon as you set some values in the azds.yaml file they are automatically set to true, whatever the value.

Is it a bug or am I doing something wrong?
