### ISSUE TITLE
Including a gitignored file still not working

### ISSUE THREAD

**Issue by ruwentos** [Azure/dev-spaces#399]
**Describe the bug**
The Bug is described already [here.](https://github.com/Azure/dev-spaces/issues/138)
 
It says: 'This should be fixed in the latest version of the CLI (1.0.20190904.13)'.

I'm using:
Azure Dev Spaces CLI
1.0.20200827.4
API v3.2

The problem is still there.

My azds.yaml:

```
build:
     dockerfile: Dockerfile.develop
     useGitIgnore: true
     ignore:
     - "!NuGet.Config"
```

When I comment out the .gitignore rule, it works.

What's the story on that fix?
