### ISSUE TITLE
Additional values in "set" section of azds.yaml don't seem to be passed to helm charts

### ISSUE THREAD

**Issue by eiximenis** [Azure/dev-spaces#67]
Hi
I have a `azds.yaml` file with following  `set` section:

```yaml
install:
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to [space.s.]webmvc.<guid>.<region>.aksapp.io
      - $(spacePrefix)webmvc$(hostSuffix)
    inf:
      k8s:
        dns: $(spacePrefix)webmvc$(hostSuffix)
```

I access to `Values.inf.k8s.dns` in my helm chart templates, but when launched using `azds up` the values are not received. If launched helm direcly from CLI with `--set inf.k8s.dns=foo.bar` everything works as expected.

I have following version of azds CLI:

```
Azure Dev Spaces CLI (Preview)
0.1.20190228.12
API v2.15
```

Thanks!
